<a href="https://colab.research.google.com/github/lakshmi1444/teju_practice/blob/master/pandas_and_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [1]:
import pandas as pd
import numpy as np

 

In [2]:
np.__version__

'1.18.5'

In [3]:
L = list(range(10))

In [4]:
[str(i) for i in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [6]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,2),dtype="float32")

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [8]:
np.full((3,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [9]:
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
np.random.normal(0,1,(3,3))

array([[-0.65239289, -0.07863026, -0.34703732],
       [-1.02472803, -0.71908175,  0.17433548],
       [ 1.03401187, -2.61450096, -0.2770401 ]])

In [14]:
np.random.randn(3,3)

array([[-0.28425104,  0.6066907 ,  1.24719191],
       [-0.58584286,  0.75089727, -0.19076522],
       [-1.59786735,  1.0770811 ,  0.72066514]])

In [15]:
np.random.seed(0)

In [16]:
x1= np.random.randint(10,size=6)

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
x2= np.random.randint(10,size=(3,4))

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
np.random.randint(0,10)

8

In [21]:
x3 =np.random.randint(0,10,size=(3,2,2))

In [22]:
x3.ndim

3

In [23]:
x3.shape

(3, 2, 2)

In [24]:
x3.size  ## No of elements in an array

12

In [25]:
x1= np.random.randint(1,10,size=6)

In [26]:
x1

array([4, 9, 2, 4, 4, 4])

In [27]:
new1= np.array([5, 9, 5, 4, 8, 6])

In [28]:
new1

array([5, 9, 5, 4, 8, 6])

In [29]:
new1[0]

5

In [30]:
new1[-2]

8

In [31]:
new1[::-1]#reverse the array

array([6, 8, 4, 5, 9, 5])

In [32]:
new2 = np.random.randint(1,13,size=(3,5))

In [33]:
new2

array([[ 8,  1,  2, 10, 10],
       [ 1, 11,  5,  8,  4],
       [12,  3,  8,  3,  1]])

In [34]:
new2[2,3]

3

In [35]:
new2[2,-1]

1

In [36]:
new2[0,0]=12

In [37]:
new2

array([[12,  1,  2, 10, 10],
       [ 1, 11,  5,  8,  4],
       [12,  3,  8,  3,  1]])

In [38]:
x= np.arange(10)

In [39]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[:5]

array([0, 1, 2, 3, 4])

In [41]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [42]:
x[4:7]

array([4, 5, 6])

In [43]:
x[::2] ## return s elements at even place

array([0, 2, 4, 6, 8])

In [44]:
x[1::2] ## returns elements from first position step by two

array([1, 3, 5, 7, 9])

#Array Concatenation

In [45]:
x= np.array([1,2,3])

In [46]:
y= np.array([3,2,1])

In [47]:
x

array([1, 2, 3])

In [48]:
y

array([3, 2, 1])

In [49]:
z=[12,21,43]

In [50]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 12, 21, 43])

In [51]:
grid = np.array([[1,2,3],[4,5,6]])

In [52]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
np.vstack([z,grid])

array([[12, 21, 43],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [56]:
x= np.array([3,4,5])
grid = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
np.vstack([x,grid])

array([[3, 4, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
grid.shape

(3, 3)

In [59]:
new3 = np.array([[1],[2],[3]])

In [60]:
new3.shape

(3, 1)

In [61]:
np.hstack([grid,new3])

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [62]:
x= np.arange(10)

In [63]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x1= np.split(x,5)

In [65]:
x1

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [66]:
np.split(x,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [67]:
 np.split(x,[3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [68]:
np.split(x, [3, 5,10])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([], dtype=int64)]

In [69]:
grid =np.arange(16).reshape(4,4)

In [70]:
 x3,x4= np.split(grid,[2])

In [71]:
x3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
x4

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#Pandas

In [73]:
data=pd.DataFrame({"country":['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})

In [74]:
data

country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [75]:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [77]:
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [78]:
data.sort_values(by="ounces")

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [79]:
data.sort_values(by=['group','ounces'],ascending=[True,True],inplace=False)

group  ounces
1     a     3.0
0     a     4.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [80]:
"one"*3

'oneoneone'

In [81]:
["one"]*3+ ['two']*4

['one', 'one', 'one', 'two', 'two', 'two', 'two']

In [82]:
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})

In [83]:
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [84]:
data.sort_values(by="k2")

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [85]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [86]:
data.drop_duplicates(subset="k2") # remove duplicates based on a particular column

k1  k2
0  one   3
1  one   2
2  one   1
5  two   4

In [87]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [88]:
data.head()

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5

In [89]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [90]:
data["animal"]= data["food"].map(str.lower).map(meat_to_animal)

In [91]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [92]:
lower1 = lambda x :x.lower()

In [93]:
data["food"] = data["food"].apply(lower1)

In [94]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [95]:
data['animal3'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal animal3
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [96]:
data.assign(new_variable= data["ounces"]*10)

food  ounces  animal animal3  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [97]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [98]:
data.replace(-999,np.NaN,inplace=True)

In [99]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [100]:
data.rename(index={"Ohio":"p"},inplace=True)

In [101]:
data.rename(columns={"one":"1"},inplace=True)

In [102]:
data

1  two  three  four
p         0    1      2     3
Colorado  4    5      6     7
New York  8    9     10    11

In [103]:
data.rename (index = str.upper,columns = str.title,inplace =True)

In [104]:
data

1  Two  Three  Four
P         0    1      2     3
COLORADO  4    5      6     7
NEW YORK  8    9     10    11

In [105]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [106]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)

'(' means the value is included in the bin, '[' means the value is excluded

In [107]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [108]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [109]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [110]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [111]:

pd.value_counts(new_cats).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

In [112]:
list('ABCD')

['A', 'B', 'C', 'D']

In [113]:
dates = pd.date_range('20130101',periods=6)

In [114]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [115]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.045759 -0.187184  1.532779  1.469359
2013-01-02  0.154947  0.378163 -0.887786 -1.980796
2013-01-03 -0.347912  0.156349  1.230291  1.202380
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018
2013-01-05 -1.706270  1.950775 -0.509652 -0.438074
2013-01-06 -1.252795  0.777490 -1.613898 -0.212740

In [116]:
df["20130101":"20130104"]

A         B         C         D
2013-01-01  0.045759 -0.187184  1.532779  1.469359
2013-01-02  0.154947  0.378163 -0.887786 -1.980796
2013-01-03 -0.347912  0.156349  1.230291  1.202380
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018

In [117]:
df.loc[:,["A","B"]]

A         B
2013-01-01  0.045759 -0.187184
2013-01-02  0.154947  0.378163
2013-01-03 -0.347912  0.156349
2013-01-04 -0.387327 -0.302303
2013-01-05 -1.706270  1.950775
2013-01-06 -1.252795  0.777490

In [118]:
df.iloc[3]

A   -0.387327
B   -0.302303
C   -1.048553
D   -1.420018
Name: 2013-01-04 00:00:00, dtype: float64

In [119]:
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
df2

A         B         C         D      E
2013-01-01  0.045759 -0.187184  1.532779  1.469359    one
2013-01-02  0.154947  0.378163 -0.887786 -1.980796    one
2013-01-03 -0.347912  0.156349  1.230291  1.202380    two
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018  three
2013-01-05 -1.706270  1.950775 -0.509652 -0.438074   four
2013-01-06 -1.252795  0.777490 -1.613898 -0.212740  three

In [120]:
df2[df2["E"].isin(["two","four"])]

A         B         C         D     E
2013-01-03 -0.347912  0.156349  1.230291  1.202380   two
2013-01-05 -1.706270  1.950775 -0.509652 -0.438074  four

In [121]:
df2[~df2["E"].isin(["two","four"])]

A         B         C         D      E
2013-01-01  0.045759 -0.187184  1.532779  1.469359    one
2013-01-02  0.154947  0.378163 -0.887786 -1.980796    one
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018  three
2013-01-06 -1.252795  0.777490 -1.613898 -0.212740  three

In [122]:
df.query('A>C')

A         B         C         D
2013-01-02  0.154947  0.378163 -0.887786 -1.980796
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018
2013-01-06 -1.252795  0.777490 -1.613898 -0.212740

In [123]:
df.query("A>B |A>C")

A         B         C         D
2013-01-01  0.045759 -0.187184  1.532779  1.469359
2013-01-02  0.154947  0.378163 -0.887786 -1.980796
2013-01-04 -0.387327 -0.302303 -1.048553 -1.420018
2013-01-06 -1.252795  0.777490 -1.613898 -0.212740

In [124]:
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [125]:
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [126]:
data.groupby("group").mean()

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [127]:
data.pivot_table(values="ounces",index = "group",aggfunc=np.mean)

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [128]:
data.pivot_table(values="ounces",index = "group",aggfunc="count")

ounces
group        
a           3
b           3
c           3

In [130]:
train = pd.read_csv("train.csv")

In [131]:
test = pd.read_csv("test.csv")

In [132]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8987 entries, 0 to 8986
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             8987 non-null   int64  
 1   workclass       8455 non-null   object 
 2   fnlwgt          8987 non-null   int64  
 3   education       8987 non-null   object 
 4   education.num   8987 non-null   int64  
 5   marital.status  8987 non-null   object 
 6   occupation      8453 non-null   object 
 7   relationship    8986 non-null   object 
 8   race            8986 non-null   object 
 9   sex             8986 non-null   object 
 10  capital.gain    8986 non-null   float64
 11  capital.loss    8986 non-null   float64
 12  hours.per.week  8986 non-null   float64
 13  native.country  8822 non-null   object 
 14  target          8986 non-null   object 
dtypes: float64(3), int64(3), object(9)
memory usage: 1.0+ MB


In [133]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16281 entries, 0 to 16280
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             16281 non-null  int64 
 1   workclass       15318 non-null  object
 2   fnlwgt          16281 non-null  int64 
 3   education       16281 non-null  object
 4   education.num   16281 non-null  int64 
 5   marital.status  16281 non-null  object
 6   occupation      15315 non-null  object
 7   relationship    16281 non-null  object
 8   race            16281 non-null  object
 9   sex             16281 non-null  object
 10  capital.gain    16281 non-null  int64 
 11  capital.loss    16281 non-null  int64 
 12  hours.per.week  16281 non-null  int64 
 13  native.country  16007 non-null  object
 14  target          16281 non-null  object
dtypes: int64(6), object(9)
memory usage: 1.9+ MB


In [134]:
train.shape

(8987, 15)

In [135]:
test.shape

(16281, 15)

In [136]:
train.head()

age          workclass  fnlwgt  ... hours.per.week  native.country  target
0   39          State-gov   77516  ...           40.0   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...           13.0   United-States   <=50K
2   38            Private  215646  ...           40.0   United-States   <=50K
3   53            Private  234721  ...           40.0   United-States   <=50K
4   28            Private  338409  ...           40.0            Cuba   <=50K

[5 rows x 15 columns]

In [137]:
train.isnull().sum()

age                 0
workclass         532
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        534
relationship        1
race                1
sex                 1
capital.gain        1
capital.loss        1
hours.per.week      1
native.country    165
target              1
dtype: int64

In [138]:
train.pivot_table(values="target",index = "education",aggfunc="count")

target
education            
 10th             262
 11th             327
 12th              97
 1st-4th           43
 5th-6th           75
 7th-8th          185
 9th              143
 Assoc-acdm       293
 Assoc-voc        381
 Bachelors       1463
 Doctorate        104
 HS-grad         2907
 Masters          471
 Preschool         16
 Prof-school      155
 Some-college    2064

In [139]:
test.isnull().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        966
relationship        0
race                0
sex                 0
capital.gain        0
capital.loss        0
hours.per.week      0
native.country    274
target              0
dtype: int64

In [140]:
train.select_dtypes(include=["O"])

workclass      education  ...  native.country  target
0             State-gov      Bachelors  ...   United-States   <=50K
1      Self-emp-not-inc      Bachelors  ...   United-States   <=50K
2               Private        HS-grad  ...   United-States   <=50K
3               Private           11th  ...   United-States   <=50K
4               Private      Bachelors  ...            Cuba   <=50K
...                 ...            ...  ...             ...     ...
8982       Self-emp-inc        HS-grad  ...   United-States    >50K
8983            Private        5th-6th  ...           Italy   <=50K
8984            Private   Some-college  ...   United-States   <=50K
8985                NaN      Assoc-voc  ...          Mexico   <=50K
8986            Private   Some-college  ...             NaN     NaN

[8987 rows x 9 columns]

In [141]:
train.apply(pd.Series.nunique)

age                 71
workclass            8
fnlwgt            7768
education           16
education.num       16
marital.status       8
occupation          14
relationship         6
race                 5
sex                  2
capital.gain        99
capital.loss        73
hours.per.week      81
native.country      40
target               2
dtype: int64

In [142]:
train.workclass.value_counts(sort=True)

 Private             6240
 Self-emp-not-inc     723
 Local-gov            570
 State-gov            354
 Self-emp-inc         318
 Federal-gov          248
 Never-worked           1
 Without-pay            1
Name: workclass, dtype: int64

In [143]:
train.isnull().sum()

age                 0
workclass         532
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        534
relationship        1
race                1
sex                 1
capital.gain        1
capital.loss        1
hours.per.week      1
native.country    165
target              1
dtype: int64

In [144]:
train['native.country'].value_counts(sort=True)
train['native.country'].fillna('United-States',inplace=True)

In [145]:
train.occupation.value_counts(sort=True)

 Prof-specialty       1131
 Exec-managerial      1094
 Craft-repair         1087
 Adm-clerical         1068
 Sales                1054
 Other-service         910
 Machine-op-inspct     559
 Transport-moving      453
 Handlers-cleaners     351
 Farming-fishing       264
 Tech-support          262
 Protective-serv       180
 Priv-house-serv        38
 Armed-Forces            2
Name: occupation, dtype: int64

In [146]:
train.occupation.fillna("Prof-specialty",inplace =True)

In [147]:
train.workclass.fillna("Private",inplace=True)

In [148]:
train.dropna(axis=0,how="any",inplace=True)

In [149]:
train.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
target            0
dtype: int64

In [150]:
train.target.value_counts(normalize=True)

 <=50K    0.760628
 >50K     0.239372
Name: target, dtype: float64

In [151]:
pd.crosstab(train.education,train.target)

target          <=50K   >50K
education                   
 10th             240     22
 11th             313     14
 12th              91      6
 1st-4th           42      1
 5th-6th           69      6
 7th-8th          169     16
 9th              137      6
 Assoc-acdm       217     76
 Assoc-voc        289     92
 Bachelors        866    597
 Doctorate         24     80
 HS-grad         2409    498
 Masters          208    263
 Preschool         16      0
 Prof-school       41    114
 Some-college    1704    360

In [152]:
pd.crosstab(train.education,train.target,margins=True,normalize=True)

target            <=50K      >50K       All
education                                  
 10th          0.026708  0.002448  0.029156
 11th          0.034832  0.001558  0.036390
 12th          0.010127  0.000668  0.010795
 1st-4th       0.004674  0.000111  0.004785
 5th-6th       0.007679  0.000668  0.008346
 7th-8th       0.018807  0.001781  0.020588
 9th           0.015246  0.000668  0.015914
 Assoc-acdm    0.024149  0.008458  0.032606
 Assoc-voc     0.032161  0.010238  0.042399
 Bachelors     0.096372  0.066437  0.162809
 Doctorate     0.002671  0.008903  0.011574
 HS-grad       0.268084  0.055420  0.323503
 Masters       0.023147  0.029268  0.052415
 Preschool     0.001781  0.000000  0.001781
 Prof-school   0.004563  0.012686  0.017249
 Some-college  0.189628  0.040062  0.229691
All            0.760628  0.239372  1.000000